# Generated by Django 4.2.21 on 2025-05-15 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metro_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name': 'Назначение', 'verbose_name_plural': 'Назначения'},
        ),
        migrations.AlterModelOptions(
            name='assistancerequest',
            options={'verbose_name': 'Запрос на помощь', 'verbose_name_plural': 'Запросы на помощь'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='metrostation',
            options={'verbose_name': 'Станция метро', 'verbose_name_plural': 'Станции метро'},
        ),
        migrations.AlterModelOptions(
            name='passenger',
            options={'verbose_name': 'Пассажир', 'verbose_name_plural': 'Пассажиры'},
        ),
        migrations.AlterField(
            model_name='assignment',
            name='employees',
            field=models.ManyToManyField(to='metro_app.employee', verbose_name='Сотрудники'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Заметки'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='metro_app.assistancerequest', verbose_name='Запрос'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='start_time',
            field=models.DateTimeField(verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='assistancerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='assistancerequest',
            name='end_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_requests', to='metro_app.metrostation', verbose_name='Станция прибытия'),
        ),
        migrations.AlterField(
            model_name='assistancerequest',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metro_app.passenger', verbose_name='Пассажир'),
        ),
        migrations.AlterField(
            model_name='assistancerequest',
            name='requested_time',
            field=models.DateTimeField(verbose_name='Запрошенное время'),
        ),
        migrations.AlterField(
            model_name='assistancerequest',
            name='start_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_requests', to='metro_app.metrostation', verbose_name='Станция отправления'),
        ),
        migrations.AlterField(
            model_name='assistancerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('assigned', 'Назначена'), ('in_progress', 'В процессе'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='assistancerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='current_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='metro_app.metrostation', verbose_name='Текущая станция'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступен'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='metrostation',
            name='latitude',
            field=models.FloatField(verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='metrostation',
            name='line',
            field=models.CharField(max_length=50, verbose_name='Линия'),
        ),
        migrations.AlterField(
            model_name='metrostation',
            name='longitude',
            field=models.FloatField(verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='metrostation',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='additional_info',
            field=models.TextField(blank=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='has_luggage',
            field=models.BooleanField(default=False, verbose_name='Есть багаж'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='type',
            field=models.CharField(choices=[('visually_impaired', 'Слабовидящий'), ('wheelchair', 'Колясочник')], max_length=20, verbose_name='Тип пассажира'),
        ),
    ]
